In [1]:
import numpy as np
import pandas as pd

# 7.2 Self Check


### 2. (IPython Session)
#### Create a one-dimensional `array` from a list comprehension that produces the even integers from 2 through 20.


In [2]:
np.array([i for i in range(2,21) if i % 2 == 0])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### 3. (IPython Session)
#### Create a 2-by-5 `array` containing the even integers from 2 through 10 in the first row and the odd integers from 1 through 9 in the second row.


In [3]:
number = np.array([[1,3,5,7,9],[2,4,6,8,10]])

# 7.3 Self Check


### 2. (IPython Session)
#### For the two-dimensional array in the previous section’s Self Check, display the number of dimensions and shape of the array.


In [4]:
a = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

In [5]:
a.size

10

In [6]:
a.shape

(2, 5)

In [7]:
a.ndim

2

# 7.5 Self Check


### 2. (IPython Session)
#### Use NumPy function `arange` to create an `array` of 20 even integers from 2 through 40,
#### then reshape the result into a 4-by-5 `array`.


In [8]:
np.arange(2,41,2).reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

# 7.6 Self Check


### 1. (IPython Session)
#### Use `%timeit` to compare the execution time of the following two statements.
#### The first uses a list comprehension to create a list of the integers from 0 to 9,999,999
#### then totals them with the built-in `sum` function.
#### The second statement does the same thing using an `array` and its `sum` method.


In [9]:
%timeit sum([x for x in range(100_000_000)])

3.75 s ± 21.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
%timeit np.arange(100_000_000).sum()

205 ms ± 5.88 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
%timeit np.arange(100_000_000, dtype='int16').sum()

90.9 ms ± 808 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 7.7 Self Check


### 2. (IPython Session)
#### Create an array of the values from 1 through 5 then use broadcasting to square each value.


In [12]:
np.arange(1,6) ** 2

array([ 1,  4,  9, 16, 25])

# 7.8 Self Check


### 2. (IPython Session)
#### Use NumPy random-number generation to create an array of twelve random grades in the range 60 through 100,
#### then reshape the result into a 3-by-4 array.
#### Calculate the average of all the grades, the averages of the grades in each column and the averages of the grades in each row.


In [13]:
numbers = np.random.randint(60,101,12).reshape(3,4)

In [14]:
numbers.sum()/len(numbers)

np.float64(335.0)

In [15]:
numbers.mean()

np.float64(83.75)

In [16]:
numbers.mean(axis=0)

array([88.66666667, 70.33333333, 94.        , 82.        ])

In [17]:
numbers.mean(axis=1)

array([89.75, 77.  , 84.5 ])

# 7.9 Self Check


### 2. (IPython Session)
#### Create an array of the values from 1 through 5 then use the `power` universal function and broadcasting to cube each value.


In [18]:
numbers = np.arange(1,6)

In [19]:
np.power(numbers, 3)

array([  1,   8,  27,  64, 125])

# 7.10 Self Check


### 1. (IPython Session)
#### Given the following array:
#### array([[ 1,  2,  3,  4,  5],
####        [ 6,  7,  8,  9, 10],
####        [11, 12, 13, 14, 15]])

#### Write statements to perform the following tasks:
#### a. Select the second row.
#### b. Select the first and third rows.
#### c. Select the middle three columns.

In [20]:
numbers = np.array([[ 1,  2,  3,  4,  5],
                    [ 6,  7,  8,  9, 10],
                    [11, 12, 13, 14, 15]])

In [21]:
numbers[1:2]

array([[ 6,  7,  8,  9, 10]])

In [22]:
numbers[[0,2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [23]:
numbers[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

# 7.13 Self Check

1. *(IPython Session)* Given a 2-by-3 array:

```python
array([[1, 2, 3],
       [4, 5, 6]])
```

use `hstack` and `vstack` to produce the following array:

```python
array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])
```


In [37]:
number = np.array([[1, 2, 3],[4, 5, 6]])

In [38]:
# print(number)
number = np.hstack([number, number])
# print(number)
np.vstack([number, number])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# 7.14.1 Self Check

1. *(IPython Session)* Use the NumPy’s random number generation to create an `array` of five random integers that represent summertime temperatures in the range 60–100, then perform the following tasks:

a. Convert the `array` into the `Series` named `temperatures` and display it.

b. Determine the lowest, highest and average temperatures.

c. Produce descriptive statistics for the `Series`.


In [16]:
temperatures = pd.Series(np.random.randint(60,101, 5))

In [17]:
temperatures

0    93
1    98
2    60
3    89
4    76
dtype: int32

In [18]:
temperatures.min()

np.int32(60)

In [19]:
temperatures.max()

np.int32(98)

In [20]:
temperatures.mean()

np.float64(83.2)

In [21]:
temperatures.describe()

count     5.000000
mean     83.200000
std      15.319922
min      60.000000
25%      76.000000
50%      89.000000
75%      93.000000
max      98.000000
dtype: float64